version: 2
executorType: machine
stages:
  build:
    workDir: ~/gradle-docker
    environment:
      TERM: dumb
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: ./gradlew --parallel -i build
      - type: test-results-store
        path: build/test-results
      - type: deploy
        shell: /bin/bash
        command: ./gradlew -i bintrayUpload
      - type: deploy
        shell: /bin/bash
        command: ./gradlew -i -Dgradle.publish.key=$GRADLE_KEY -Dgradle.publish.secret=$GRADLE_SECRET publishPlugins

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            # run on all branches and tags
            tags:
              only: /.*/
