version: 2
executorType: machine
stages:
  build:
    workDir: ~/gradle-docker
    environment:
      TERM: dumb
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: ./gradlew --parallel -i build
      - type: test-results-store
        path: $CIRCLE_TEST_REPORTS
